# Site settings
title: Sagar Hani
email: sagarhani33@gmail.com
description: Sagar Hani - God will bless for those who contribute to FOSS.
baseurl: "" 
url: "http://sagarhani.in" 
twitter_username: sagarhan_i
github_username:  sagarhani

# Build settings
markdown: kramdown
